#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-wallpapers
Version  : 7
Release  : 18
URL      : https://github.com/clearlinux/clr-wallpapers/archive/v7.tar.gz
Source0  : https://github.com/clearlinux/clr-wallpapers/archive/v7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Distributable
Requires: clr-wallpapers-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the clr-wallpapers package.
Group: Data

%description data
data components for the clr-wallpapers package.


%prep
%setup -q -n clr-wallpapers-7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555022499
export LDFLAGS="${LDFLAGS} -fno-lto"
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1555022499
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/backgrounds/clearlinux/Wire_2560x1440.png
/usr/share/backgrounds/clearlinux/background_01.png
/usr/share/backgrounds/clearlinux/background_02.png
/usr/share/backgrounds/clearlinux/background_03.png
/usr/share/backgrounds/clearlinux/background_04.png
/usr/share/backgrounds/clearlinux/background_05.png
/usr/share/backgrounds/clearlinux/background_06.png
/usr/share/backgrounds/clearlinux/background_07.png
/usr/share/backgrounds/clearlinux/background_08.png
/usr/share/backgrounds/clearlinux/color_logo_wire_2560x1440.png
/usr/share/backgrounds/clearlinux/lockscreen_4K_01.png
/usr/share/backgrounds/clearlinux/logo_2560x1440.png
/usr/share/backgrounds/clearlinux/wallpaper_4K_01.jpg
/usr/share/backgrounds/clearlinux/wallpaper_4K_02.jpg
/usr/share/backgrounds/clearlinux/wallpaper_4K_03.jpg
/usr/share/backgrounds/clearlinux/wallpaper_4K_05.png
/usr/share/backgrounds/xfce/wallpaper_4K_01.jpg
/usr/share/backgrounds/xfce/wallpaper_4K_02.jpg
/usr/share/backgrounds/xfce/wallpaper_4K_03.jpg
/usr/share/gnome-background-properties/clearlinux-backgrounds.xml
/usr/share/gnome-background-properties/clr-wallpapers.xml
